# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  javadoc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14.0.2
      uses: actions/setup-java@v1
      with:
        java-version: '14.0.2'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate Javadoc with Gradle
      run: ./gradlew javadoc
    - name: Copy Javadoc to docs/ folder
      run: cp -r build/docs/javadoc docs/
